blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns=[
    path("",views.index,name="index"),
    
    # path("post/<int:post_id>",views.details,name="details")
    path("post/<str:slug>",views.details,name="details"),

    path("old_url",views.old_url,name="old_url"),
    # path("new_url>",views.new_url,name="new_url"),
    path("contact",views.contact_view,name="contact"),
    path("about",views.about_view,name="about"),
    path("new_something_url",views.new_url,name="new_page_url"),

]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'myapp.views.custom_page_not_found'


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
]

blog/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, max_length=255)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class AboutUs(models.Model):
    content=models.TextField()
    

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
import logging
from .models import Post,AboutUs
from django.core.paginator import Paginator
from .form import ContactForm

# static demo data
# post = [
#     {"id": 1, "title": "Post 1", "content": "Content of Post 1"},
#     {"id": 2, "title": "Post 2", "content": "Content of Post 2"},
#     {"id": 3, "title": "Post 3", "content": "Content of Post 3"},
#     {"id": 4, "title": "Post 4", "content": "Content of Post 4"},
#     {"id": 5, "title": "Post 5", "content": "Content of Post 5"},
# ]

# Create your views here.
# def index(request):
#     return HttpResponse("Hlo World, You at blog's index")


def index(request):
    blog_title = "Latest Post of Index Page"
    all_post = Post.objects.all()
    
    paginator=Paginator(all_post,3)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    return render(request, "blog/index.html", {"blog_title": blog_title, "page_obj": page_obj})


# def details(request,post_id):
#     return HttpResponse(f"You are viewing post detail page, POST ID: {post_id}")


def details(request, slug):

    # static data
    # postData = next((item for item in post if item["id"] == int(post_id)), None)

    # logging
    # logger = logging.getLogger("Testing")
    # logger.debug(f'post variable {postData}')

    try:
        postData = Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category=postData.category).exclude(pk=postData.id)
    except Post.DoesNotExist:
        raise Http404("Post id does not match")

    return render(request, "blog/details.html", {"postData": postData,"related_posts":related_posts})


# def old_url(request):
#     return redirect("new_url")


def old_url(request):
    return redirect(reverse("blog:new_page_url"))


def new_url(request):
    return HttpResponse("This is new Url")

def contact_view(request):
    if request.method=="POST":
        
        form=ContactForm(request.POST)
        name=request.POST.get('name')
        email=request.POST.get('email')
        message=request.POST.get('message')
        
        logger = logging.getLogger("Testing")
        
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            logger.debug(f'post variable name: {name}, email: {email}, message: {message}')
            success_message='Your Email has beed send'
            return render(request,"blog/contact.html",{"form":form,"success_message":success_message})
        else:
            logger.debug('Form validation failure')
        return render(request,"blog/contact.html",{'form':form,'name':name,'email':email,'message':message})
    return render(request,"blog/contact.html")

def about_view(request):
    about_content=AboutUs.objects.first().content
    return render(request,"blog/about.html",{'about_content':about_content})

myapp/views.py
from django.shortcuts import render

def custom_page_not_found(request,exception):
    return render(request,'404.html',status=404)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>About Page</h2>
<p>{{about_content}}</p> 
{% endblock %}

blog/templates/blog/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:"Document"}}</title>
    <link href="{% static 'blog/style.css' %}" rel="stylesheet" />

</head>

<body>
    <!-- Header Content -->
    {% include 'blog/includes/header.html' %}

    <!-- Dynamic Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer Content -->
    {% include 'blog/includes/footer.html' %}

</body>

</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
  <div>
    {% comment %} error {% endcomment %}
    {% for field in form%}
    {% if field.errors %}
    <div>
      <span>{{field.label_tag}}</span>
      {% for error in  field.errors%}
      <span>{{error}}</span>
      {% endfor %}
    {% endif %}
    {% endfor %}

    {% comment %} success {% endcomment %}
    {% if success_message %}
    <div>
      {{success_message}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div>
      <h1>Contact Form</h1>
      <h2>Name</h2>
      <input type="text" placeholder="Enter name" class="input" name="name" id="name" value={{name}}>
      <h2>Email</h2>
      <input type="email" placeholder="Enter email" class="input" name="email" id="email" value={{email}}>
      <h2>Message</h2>
      <textarea rows="4" name="message" id="message" value={{message}}></textarea><br />
      <input class="submit" type="submit" />
        </div>
    </form>
  </div>
{% endblock %}

blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% block content %}
  <div>
    <h1>Details Page</h1>
    <h2>{{ postData.title }}  ({{postData.category.name}})</h2>
    <p>Posted on: {{ postData.created_at|date:'F j, Y' }} --- {{ postData.created_at }}</p>
    <div class="img-post">
      <img src="{{ postData.img_url }}" height="400" width="500" />
      <div>
        <h2>Related Post :</h2>
        {% for related_post in related_posts %}
          <h3><a href="{% url 'blog:details' slug=related_post.slug %}">{{related_post.title}}</a></h3>
        {% endfor %}
      </div>
    </div>
    <h3>Content: {{ postData.content }}</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, praesentium voluptatum molestiae laborum odio nulla cum possimus dolorum quam illum maxime deserunt quaerat facilis doloribus laudantium, corrupti quo. Quia, tenetur?</p>
  </div>
{% endblock %}

blog/templates/blog/includes/footer.html
<footer>
    <h1>Footer</h1>
    <div class="foot flex" >
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </div>
</footer>

blog/templates/blog/includes/header.html
<nav>
    <h1><a href="/" style="color: white; text-decoration: none;">Blog</a></h1>
    <div class="links flex">
        <a href="/"><h1>Home</h1></a>
        <a href="/about"><h1>About</h1></a>
        <a href="/contact"><h1>Contact</h1></a>
    </div>
</nav>  

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>Index Page</h2>
  <h2>{{ blog_title|lower }} : {{ blog_title|length }} : {{ blog_title|truncatewords:1 }}</h2>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, praesentium voluptatum molestiae laborum odio nulla cum possimus dolorum quam illum maxime deserunt quaerat facilis doloribus laudantium, corrupti quo. Quia, tenetur?</p>
  {% if page_obj %}
    <div class="posts">
      {% for item in page_obj %}
        <div class="post">
          <img src={{item.img_url}} height="150" width="350"/>
          <h2>{{ item.title }}</h2>
          <p>{{ item.content | truncatechars:70}}</p>
          <a href="{% url 'blog:details' slug=item.slug %}"> Read More...</a>
          <h4>{{item.category.name}}</h4>
          {% comment %} <a href="/blog/post/{{item.id}}"> Read More...</a> {% endcomment %}
        </div>
      {% endfor %}
      {% if page_obj.has_other_pages%}
      <div class="pagination">
        {% if page_obj.has_previous%}
        <h2><a href="?page=1">first</a></h2>
        <h2><a href="?page={{page_obj.previous_page_number}}">previous</a></h2>
        {% endif%}
        <h2><a href="?page=1">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</a> </h2>
        {% if page_obj.has_next%}
        <h2><a href="?page={{page_obj.next_page_number}}">next</a></h2>
        <h2><a href="?page={{page_obj.paginator.num_pages}}">last</a></h2>
        {% endif%}
      </div>
      {% endif%}
    </div>
  {% else %}
    <p>No Post</p>
  {% endif %}
{% endblock %}